import { ArrowLeft, Check, FileCheck2, ShieldCheck } from "lucide-react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import PageHeader from "@/components/site/PageHeader";

const checks = ["هویت و مشخصات ثبتی", "سابقه فعالیت و حضور بازار", "اطلاعات تماس و آدرس", "توان تولید یا تأمین", "سوابق تجاری", "بررسی اسناد و گواهی‌ها", "مالکیت و ساختار شرکت", "توان پاسخ‌گویی و ارتباط", "شرایط پرداخت و معامله", "ریسک‌های عملیاتی", "نشانه‌های هشدار", "جمع‌بندی و امتیاز ریسک"];
const steps = [["۰۱", "دریافت درخواست", "اطلاعات شرکت و نوع معامله مشخص می‌شود."], ["۰۲", "دریافت مدارک", "اسناد و اطلاعات مورد نیاز برای بررسی دریافت می‌شود."], ["۰۳", "بررسی و تحلیل", "اطلاعات در چند محور بررسی و ریسک‌های مهم شناسایی می‌شوند."], ["۰۴", "گزارش نهایی", "نتیجه بررسی و جمع‌بندی ریسک در قالب گزارش ارائه می‌شود."]];

export default function SupplierVerificationPage() {
  return (
    <main>
      <Header />
      <PageHeader eyebrow="اعتبارسنجی تأمین‌کنندگان" title="پیش از معامله، طرف تجاری خود را بهتر بشناسید." description="یک سرویس ساختاریافته برای بررسی تأمین‌کنندگان و کاهش ریسک تصمیم‌گیری پیش از خرید و همکاری بین‌المللی." actionHref="/supplier-verification/request" actionLabel="درخواست اعتبارسنجی" />
      <section className="bg-[#f3f2ed] py-20 lg:py-28"><div className="container-site"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:items-start"><div><p className="text-sm font-bold text-[#98783f]">چرا اعتبارسنجی؟</p><h2 className="mt-4 font-display text-3xl font-black leading-[1.3] sm:text-5xl">اطمینان بیشتر، قبل از تعهد.</h2></div><div className="max-w-3xl text-sm leading-8 text-[#686963]"><p>در خرید بین‌المللی، شناخت محصول به اندازه شناخت فروشنده اهمیت دارد. اعتبارسنجی به شما کمک می‌کند پیش از پرداخت یا عقد قرارداد، تصویر روشن‌تری از طرف تجاری داشته باشید.</p><div className="mt-10 grid gap-4 sm:grid-cols-3"><div className="border-t border-black/10 pt-4 font-bold">کاهش ریسک</div><div className="border-t border-black/10 pt-4 font-bold">تصمیم مستند</div><div className="border-t border-black/10 pt-4 font-bold">دید شفاف‌تر</div></div></div></div></div></section>
      <section className="bg-[#171816] py-20 text-white lg:py-28"><div className="container-site"><div className="mb-12 max-w-2xl"><p className="text-sm font-bold text-[#c9a66b]">استعلام‌های ۱۲گانه</p><h2 className="mt-4 font-display text-3xl font-black sm:text-5xl">بررسی از چند زاویه، نه فقط یک مدرک.</h2></div><div className="grid border-t border-white/10 sm:grid-cols-2 lg:grid-cols-3">{checks.map((check, index) => <div key={check} className="flex items-center gap-4 border-b border-white/10 p-5 text-sm text-white/75"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-white/10 text-xs text-[#c9a66b]">{String(index + 1).padStart(2, "0")}</span>{check}</div>)}</div></div></section>
      <section className="bg-[#f3f2ed] py-20 lg:py-28"><div className="container-site"><div className="mb-12 max-w-2xl"><p className="text-sm font-bold text-[#98783f]">فرآیند اعتبارسنجی</p><h2 className="mt-4 font-display text-3xl font-black sm:text-5xl">از درخواست تا گزارش نهایی.</h2></div><div className="grid border-t border-black/10 md:grid-cols-2 lg:grid-cols-4">{steps.map(([number, title, text]) => <div key={number} className="border-b border-black/10 p-7 lg:border-l lg:p-8 last:lg:border-l-0"><span className="text-xs text-[#98783f]">{number}</span><h3 className="mt-10 text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-[#686963]">{text}</p></div>)}</div></div></section>
      <section className="bg-[#e4e2da] py-20 lg:py-24"><div className="container-site"><div className="grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#171816] text-white"><ShieldCheck size={20} /></div><h2 className="mt-7 font-display text-3xl font-black sm:text-5xl">گزارش نهایی، برای تصمیم شما.</h2><p className="mt-5 max-w-2xl text-sm leading-8 text-[#686963]">در نسخه نهایی سرویس، نتیجه بررسی، سطح ریسک، موارد مهم و مدارک بررسی‌شده در قالب یک گزارش ساختاریافته ارائه خواهد شد.</p></div><a href="/supplier-verification/request" className="inline-flex w-fit items-center gap-3 rounded-full bg-[#171816] px-6 py-4 text-sm font-bold text-white transition hover:bg-[#98783f]">شروع درخواست<ArrowLeft size={15} /></a></div></div></section>
      <section className="bg-[#f3f2ed] py-20 lg:py-24"><div className="container-site"><div className="grid gap-5 md:grid-cols-3"><div className="rounded-3xl border border-black/10 p-7"><FileCheck2 size={20} /><h3 className="mt-6 font-black">نمونه گزارش</h3><p className="mt-3 text-sm leading-7 text-[#686963]">نمایش نمونه‌ای از ساختار گزارش اعتبارسنجی.</p></div><div className="rounded-3xl border border-black/10 p-7"><Check size={20} /><h3 className="mt-6 font-black">سطوح خدمات</h3><p className="mt-3 text-sm leading-7 text-[#686963]">سطوح مختلف بررسی متناسب با نوع معامله و نیاز شما.</p></div><div className="rounded-3xl border border-black/10 p-7"><ShieldCheck size={20} /><h3 className="mt-6 font-black">سوالات متداول</h3><p className="mt-3 text-sm leading-7 text-[#686963]">پاسخ به سوالات مهم درباره فرآیند، مدارک و خروجی سرویس.</p></div></div></div></section>
      <Footer />
    </main>
  );
}
